version: "3"
services:
    web:
        build: .
        ports:
            - "44301:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "sa"
            ACCEPT_EULA: "I10easttoLA"