# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  name: MP.Windows

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

stages:
  - stage: BuildInDebugMode
    jobs:
    - job: buildAndTest
      timeoutInMinutes: 150
      steps:
      - checkout: self
        clean: true
      
      #- template: /.pipelineTemplates/BuildAndTest.yml
      
      #- template: /.pipelineTemplates/NuGetPackagePublish.yml
    
  - stage: BuildWithoutTemplate
    jobs:
      - job: BuildWithoutTemplate
        steps:
        
        - task: UseDotNet@2
          displayName: 'Use .NET 6 SDK'
          inputs:
            packageType: sdk
            version: 6.x

        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
            feedsToUse: 'select'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/*.csproj'
