// <auto-generated />
using System;
using Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20190926152248_EmpresaCreated")]
    partial class EmpresaCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyBI.Domain1.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ativo");

                    b.Property<string>("Codclie");

                    b.Property<string>("CpfCnpj")
                        .HasColumnType("varchar(12)");

                    b.Property<DateTime?>("DataAlteracao");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<DateTime?>("DataNascimento");

                    b.Property<int>("EstadoCivil");

                    b.Property<int?>("Genero");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("varchar(14)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Rg")
                        .HasColumnType("varchar(12)");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("MyBI.Domain1.Entities.Empresa", b =>
                {
                    b.Property<int>("idRazaoSocial")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dtCadastro")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("nContato");

                    b.Property<int>("nDiaCobranca");

                    b.Property<int>("nQtdeParcelas");

                    b.Property<decimal>("nValorAproximado");

                    b.Property<string>("sCep");

                    b.Property<string>("sCidade");

                    b.Property<string>("sCnpjCpf");

                    b.Property<bool>("sCorrente");

                    b.Property<string>("sEndereco");

                    b.Property<string>("sEstado");

                    b.Property<string>("sRazaoSocial")
                        .HasColumnType("varchar(400)");

                    b.HasKey("idRazaoSocial");

                    b.ToTable("Empresa");
                });
#pragma warning restore 612, 618
        }
    }
}
